backend:
  name: github
  repo: Xaphedo/hytale-worldgen-wiki
  branch: main
  base_url: https://netlify-cms-github-oauth-provider-aww2m1utw-xaphedos-projects.vercel.app/
  auth_endpoint: 
  scope: ['public_repo']  
  open_authoring: true

publish_mode: editorial_workflow

# This creates the "Login with Netlify Identity" button
media_folder: "docs/assets/images" # Where images are saved in the repo
public_folder: "/assets/images"    # How the site links to them

# This defines what your users can edit
collections:
  - name: "pages"
    label: "Wiki Pages"
    folder: "docs" # The CMS looks for .md files in this folder
    create: true   # Allow users to create new pages
    slug: "{{slug}}" # The filename will look like 'page-title.md'
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
